# Generated by Django 4.1.2 on 2022-12-22 15:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('user', models.CharField(max_length=8, unique=True)),
                ('long', models.DecimalField(decimal_places=15, max_digits=30)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=30)),
                ('lock_stat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('stat', models.CharField(default='', max_length=8, unique=True)),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('charge_stat', models.IntegerField(default=0, max_length=3)),
            ],
        ),
    ]
