# Generated by Django 4.1.2 on 2022-12-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_charge_stat_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
