# Generated by Django 4.1.4 on 2022-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wallet_delete_stat_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='uid',
            field=models.CharField(default='Hello', max_length=100),
        ),
    ]
